stages:
  - example-stage

include:
  remote: 'https://raw.githubusercontent.com/m-yosefpor/infracost-gitlab-ci/master/infracost.yml'

example-infracost-job:
  stage: example-stage
  extends: .infracost
  variables:
    tfdir: examples/terraform
